### ISSUE TITLE
GDPR Request issue

### ISSUE THREAD

**Issue by 9harrisonc** [myCenterRBLX/Site-Issue-Tracker#1]
**Describe the bug**
The GDPR Data Request "endpoints" errors with a message: "Something did go wrong."

**To Reproduce**
I was unable to replicate this error. However that client in 4175 is having this issue.

**Expected behavior**
It is meant to download the data file.

**Screenshots**

**Desktop (please complete the following information):**
Browser.

**Smartphone (please complete the following information):**
Unknown.

**Additional context**

**Comment by mwalden2004** [comment]
Unable to reproduce the issue.
