### ISSUE TITLE
Partners Label on bottom of site

### ISSUE THREAD

**Issue by 9harrisonc** [myCenterRBLX/Site-Issue-Tracker#11]
**Describe the bug**
On mobile, only 3 partners appear in the list of partners at the bottom of the site.

**To Reproduce**
1. Go to the myCenter website on a mobile device.
2. Scroll down to where the partners list is.
3. See how not all partners are listed.

**Expected behavior**
It's expected that the website lists all partners.

**Screenshots**
https://media.discordapp.net/attachments/698269379552477215/713362166136438824/Screenshot_20200522-130614.png

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 Samsung, but probably on all.

**Additional context**

**Comment by Nickanda** [comment]
This is because the other patreons are being hidden by the bottom bar. If you tilt your screen to landscape (sideways), more patreons should appear. Not sure if we are looking into a fix for this right now.

**Comment by 9harrisonc** [comment]
Alrighty. I shall close this for now.
