### ISSUE TITLE
You can't manage applications. (Might be temporary.)

### ISSUE THREAD

**Issue by BigEd33** [myCenterRBLX/Site-Issue-Tracker#12]
**Describe the bug**
Once you click "Manage" the site just freezes and after a few minutes just turns into an error.

**To Reproduce**
1. Go to myCenter.
2. Manage any center.
3. Manage an app.
4. Wait a few minutes.
5. The website freezes.

**Expected behavior**
The application menu will open.

**Screenshots**
https://gyazo.com/0ab4c272cb6a403c63221f05b68742df
![Image 2020-05-22 at 4 10 26 PM](https://user-images.githubusercontent.com/64424537/82671021-d72e4900-9c46-11ea-9f46-b24213c95961.png)

**Desktop (please complete the following information):**
Unknown.

**Smartphone (please complete the following information):**
Unknown.

**Additional context**
None.

**Comment by Nickanda** [comment]
Maintenance related, please close @mwalden2004
