### ISSUE TITLE
Pressing the design button sends you back to the dashboard.

### ISSUE THREAD

**Issue by BigEd33** [myCenterRBLX/Site-Issue-Tracker#13]
**Describe the bug**
Once you click the design button the site will send you back to the dashboard.

**To Reproduce**
1. Go to myCenter.
2. Manage a center.
3. Manage an application.
4. Go to the admin page.
5. Click the Design button.
6. The website sends you back to the dashboard.

**Expected behavior**
The design menu will open.

**Screenshots**
https://cdn.discordapp.com/attachments/713269221357912084/713270522393133060/video0.mov

**Desktop (please complete the following information):**
Unknown.

**Smartphone (please complete the following information):**
- iPhone 8 Plus
- iOS 13.4.1
- Safari
- 13.1

**Additional context**
None.

**Comment by Nickanda** [comment]
Cannot reproduce

**Comment by BigEd33** [comment]
@Nickanda It might because of the phone version or maybe it was already fixed.
