### ISSUE TITLE
Button to create an application not appearing [question_4876]

### ISSUE THREAD

**Issue by 9harrisonc** [myCenterRBLX/Site-Issue-Tracker#14]
**Describe the bug**
The client reporting this issue is the center owner. They are unable to create applications as the button does not appear.

**To Reproduce**

**Expected behavior**

**Screenshots**
https://media.discordapp.net/attachments/713748169997025320/713749951875645470/myCenter___Tropicease_Quiz_Centre_-_Google_Chrome_23_05_2020_02_47_08_PM.png?width=1214&height=645

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Dylan-1554** [comment]
#4876

**Comment by Nickanda** [comment]
Resolved

**Comment by Nickanda** [comment]
@mwalden2004 please close c:
