### ISSUE TITLE
[CS COMMANDS] !get centers is broken.

### ISSUE THREAD

**Issue by aetheriaIs** [myCenterRBLX/Site-Issue-Tracker#15]
When you run !get centers, all it does is delete the message. It doesn't give you an error code or anything, the message just disappears and you're left with nothing.

**To Reproduce**
1. Go on a ticket
2. Run !get centers

**Expected behavior**
It was meant to show the centers of the user, however it didn't.

**Screenshots**
Couldn't screenshot.

**Additional context**
N/A

**Comment by Nickanda** [comment]
Get centers command has been working from my usage. Any ticket number in particular? @aetheriaIs

**Comment by 9harrisonc** [comment]
@Nickanda Force share is 100% broken. As the staff update means it can't add staff anymore?

**Comment by 9harrisonc** [comment]
A new system will be coming for this, I'll close this now.
