### ISSUE TITLE
Users not able to see Applications

### ISSUE THREAD

**Issue by csci0075** [myCenterRBLX/Site-Issue-Tracker#17]
**Describe the bug**
User wanted to check my applications on myCenter. User did not create the center but was still given admin on it. When the user went to myCenter, they found that my applications where gone on the Dashboard and it said 'Create a Center' or something like when making one again. The application was not deleted.

**To Reproduce**
As such there are no specific steps to follow in order to reproduce this behaviour. Clarification on the steps were given above.

**Expected behavior**
To view the applications.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 Did not fill this in as more than one user has reported this issue, hence they might have different systems, etc.

**Additional context**
N/A.

**Comment by 9harrisonc** [comment]
All staff except the center owner were removed when the new permissions update for staff was added. The center owner will need to add them back. @csci0075
