### ISSUE TITLE
Confirmation on Pass/Failed Applications Broken [#bug_4915]

### ISSUE THREAD

**Issue by 9harrisonc** [myCenterRBLX/Site-Issue-Tracker#18]
**Describe the bug**
When you pass / fail an application, the confirmation message does not appear. But it does still complete the action.

**To Reproduce**
1. Submit an application.
2. Pass / Fail / Anything else it.
3. See it no longer give a confirmation message.
4. See that even though no message appeared, it did still complete the action.

**Expected behavior**
It is meant to give the user a confirmation message when you pass / fail an applicarion.

**Screenshots**
https://gyazo.com/88e8f537354490b524ce7c41a830cc80

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 9harrisonc** [comment]
I have also been able to replicate this issue on my own center.

**Comment by Nickanda** [comment]
Looks like this was intentionally removed, is there majority support for it to be added back?

**Comment by mwalden2004** [comment]
Can confirm, done on purpose.
