### ISSUE TITLE
Application not auto closing. 

### ISSUE THREAD

**Issue by Dylan-1554** [myCenterRBLX/Site-Issue-Tracker#19]
**Describe the bug**
The client passes/fails the applicant, it does not pop up and say "successfully passed/failed" , and does not close the application automatically. She needs to close it manually. 

**To Reproduce**

**Expected behavior**
It should automatically close, and say that the user has passed/failed. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: ios, firefox, 76.0
 - firefox
 - Version 76.0

**Smartphone (please complete the following information):**
 -Works on mobile devices. 

**Additional context**
Please see ticket 4911 for for information.

**Comment by 9harrisonc** [comment]
This is intentional behaviour and not a bug. That notice/confirmation message was removed.
