### ISSUE TITLE
[DISCORD] Suggestion: Let the agents know what their rating is changing to. 

### ISSUE THREAD

**Issue by BigEd33** [myCenterRBLX/Site-Issue-Tracker#21]
**Is your feature request related to a problem? Please describe.**
No, it is not.

**Describe the solution you'd like**
The approver at the rating request channel should DM the agents what their rating is.

**Describe alternatives you've considered**
Not really needed.

**Additional context**
None.

**Comment by 9harrisonc** [comment]
Not really possible as far as I know? As we just directly change it in the database.
