### ISSUE TITLE
Adding permission levels gives a "Invalid Request". [Ticket bug_5094]

### ISSUE THREAD

**Issue by BigEd33** [myCenterRBLX/Site-Issue-Tracker#25]
**Describe the bug**
Once you create and save a permission level you get an error message.

**To Reproduce**
1. Go to myCenter dashboard.
2. Manage a center.
3. Go to the staff page.
4. Click on "Add permission level".
5. Give it a name and permissions.
6. Click "Save permission".
7. Get an error.

**Expected behavior**
The permission level will be saved.

**Screenshots**
https://bit.ly/InvalidRequestmyCenter

**Desktop (please complete the following information):**
- OS : Windows
- Browser : Microsoft Edge
- Version: 83.0.478.37

**Smartphone (please complete the following information):**
Unknown.

**Additional context**
None.

**Comment by Nickanda** [comment]
Have looked into this before and not seeing anything
