### ISSUE TITLE
Creating a question gives a "Invalid Captcha" message. [Ticket question_5234]

### ISSUE THREAD

**Issue by BigEd33** [myCenterRBLX/Site-Issue-Tracker#27]
**Describe the bug**
The user tried to create a question for his application center, he says a message popped up saying "Invalid Captcha".

**To Reproduce**
1. Go to myCenter's website.
2. Click manage for a center.
3. Click manage for an application.
4. Create a new question.
5. Get an error.

**Expected behavior**
A new question will be created.

**Screenshots**
https://media.discordapp.net/attachments/717331375245623306/717331441104715826/unknown.png?width=1205&height=678

**Desktop (please complete the following information):**
 - OS: Windows.
 - Browser: Google Chrome 
 - Version: 83.0.4103.61

**Smartphone (please complete the following information):**
Unknown.

**Additional context**
None.

**Comment by Nickanda** [comment]
Not a bug - the system thinks that the user is a bot or is behaving more like a bot. Try using a different device or do actions that make you less like a bot (less repetitive actions, etc)
