### ISSUE TITLE
Bot Offline - #question_4648

### ISSUE THREAD

**Issue by 9harrisonc** [myCenterRBLX/Site-Issue-Tracker#7]
**Describe the bug**
Automation Bot has gone offline. I can't see any issues on Database.

**To Reproduce**
N/A

**Expected behavior**
Bot is expected to be online and working (ranking after passing etc)

**Screenshots**

**Desktop (please complete the following information):**
N/A. All.

**Smartphone (please complete the following information):**
N/A. All.

**Additional context**

**Comment by Nickanda** [comment]
Bot ID and center ID?

**Comment by 9harrisonc** [comment]
Ticket was closed so I'll mark this as completed. Didn't see your comment.
