### ISSUE TITLE
Not receiving application accepted/failed DMs from Discord Bot. [question_4370]

### ISSUE THREAD

**Issue by 9harrisonc** [myCenterRBLX/Site-Issue-Tracker#8]
**Describe the bug**
A client has reported that several of their members are not receiving Direct Messages from the myCenter Discord Bot when their applications have been passed/failed. The client says they don't have the bot blocked, and that they have the setting enabled. The client also says that the users are definitely verified.

**To Reproduce**

**Expected behavior**
The client is expecting the bot to send them a DM when their application has been passed/failed.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nickanda** [comment]
Are the members who are applying in a server with the myCenter Discord bot?

**Comment by 9harrisonc** [comment]
Yes. Apparently so.

**Comment by Nickanda** [comment]
Can't solidly reproduce this issue, I have been able to receive DMs normally. We will have to deal with the issue on a case-by-case basis. Please close @mwalden2004

**Comment by 9harrisonc** [comment]
I'll close.
