### ISSUE TITLE
[DISCORD] The bot DM's the results before the applied message. (QUIZ MODE)

### ISSUE THREAD

**Issue by BigEd33** [myCenterRBLX/Site-Issue-Tracker#9]
**Describe the bug**
Once you send an application (QUIZ MODE) the bot sometimes DM's you the applied message after the results.

**To Reproduce**
1. Apply in a center with quiz mode enabled.
2. Submit the application.
3. Go to your DM's.
4. The bot sometimes DM's the results before the applied message.

**Expected behavior**
The bot was supposed to DM the applied message first then the results.

**Screenshots**
![Image 2020-05-20 at 7 46 59 AM](https://user-images.githubusercontent.com/64424537/82406414-3cc7dd00-9a6f-11ea-8748-d8b6a62c1c23.png)

**Desktop (please complete the following information):**
Unknown, all of them.
**Smartphone (please complete the following information):**
Unknown, all of them.

**Additional context**
The issue usually happens in quiz mode.

**Comment by 9harrisonc** [comment]
This could just be an issue with the connection. So I would assume that Soro's automatically grade their applications. Meaning that it sends the response at the same time.

I'm sure one of the Developers can confirm either way?

**Comment by mwalden2004** [comment]
Not a bug, just happens to happen in quiz-mode from time to time.
